/// This file is generated by Claude on Fri May 1 11:38:18 UTC 2026
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[derive(DeriveIden)]
enum Criteria {
    Table,
    Id,
    CreationTime,
    AgentId,
    Content,
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Criteria::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Criteria::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Criteria::CreationTime)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Criteria::AgentId).integer().null())
                    .col(ColumnDef::new(Criteria::Content).text().not_null())
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(Criteria::Table).to_owned())
            .await?;
        Ok(())
    }
}
