/// This file is generated by Claude on Sun Mar 29 12:02:41 UTC 2026
use sea_orm_migration::{prelude::*, schema::*};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[derive(DeriveIden)]
enum Material {
    Table,
    Id,
    Kind,
    Shasum,
}

#[derive(DeriveIden)]
enum DecisionMem {
    Table,
    Id,
    IsTruthy,
    Time,
    MaterialId,
}

#[derive(DeriveIden)]
enum Update {
    Table,
    Id,
    Key,
    Hash,
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Create `material` table first since `decision_mem` has a FK to it
        manager
            .create_table(
                Table::create()
                    .table(Material::Table)
                    .if_not_exists()
                    .col(pk_auto(Material::Id))
                    .col(integer(Material::Kind).not_null())
                    .col(string(Material::Shasum).not_null())
                    .to_owned(),
            )
            .await?;

        // Create `decision_mem` table with FK referencing `material`
        manager
            .create_table(
                Table::create()
                    .table(DecisionMem::Table)
                    .if_not_exists()
                    .col(pk_auto(DecisionMem::Id))
                    .col(boolean(DecisionMem::IsTruthy).not_null())
                    .col(timestamp_with_time_zone(DecisionMem::Time).not_null())
                    .col(integer(DecisionMem::MaterialId).not_null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_decision_mem_material_id")
                            .from(DecisionMem::Table, DecisionMem::MaterialId)
                            .to(Material::Table, Material::Id)
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        // Create `update` table — no FK dependencies
        manager
            .create_table(
                Table::create()
                    .table(Update::Table)
                    .if_not_exists()
                    .col(pk_auto(Update::Id))
                    .col(string(Update::Key).not_null().unique_key())
                    .col(big_unsigned(Update::Hash).not_null())
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Drop in reverse order to respect FK constraints
        manager
            .drop_table(Table::drop().table(DecisionMem::Table).to_owned())
            .await?;

        manager
            .drop_table(Table::drop().table(Material::Table).to_owned())
            .await?;

        manager
            .drop_table(Table::drop().table(Update::Table).to_owned())
            .await?;

        Ok(())
    }
}
