pub fn tag<'s>(
    res: &'s str,
    start_tag: impl AsRef<str>,
    end_tag: impl AsRef<str>,
) -> Option<(String, &'s str)> {
    let Some((left, right)) = res.split_once(end_tag.as_ref()) else {
        return None;
    };
    let Some((lleft, lright)) = left.split_once(start_tag.as_ref()) else {
        return Some((right.trim_start().into(), left.trim()));
    };
    return Some((
        format!("{}\n{}", lleft.trim_end(), right.trim_start())
            .trim()
            .into(),
        lright.trim(),
    ));
}

#[cfg(test)]
mod test {
    use crate::llm::dialog::parse::tag;

    #[test]
    fn tag_middle() {
        let res = "foo\n<|think|>\nbar\n<|/think|>\nbaz";
        let (rest, reasoning) = tag(res, "<|think|>", "<|/think|>").unwrap();
        assert_eq!(rest, "foo\nbaz");
        assert_eq!(reasoning, "bar");
    }

    #[test]
    fn tag_end() {
        let res = "foo\n<|think|>\nbar\n<|/think|>";
        let (rest, reasoning) = tag(res, "<|think|>", "<|/think|>").unwrap();
        assert_eq!(rest, "foo");
        assert_eq!(reasoning, "bar");
    }

    #[test]
    fn tag_start() {
        let res = "<|think|>\nfoo\n<|/think|>\nbar";
        let (rest, reasoning) = tag(res, "<|think|>", "<|/think|>").unwrap();
        assert_eq!(rest, "bar");
        assert_eq!(reasoning, "foo");
    }
}

/// This module is partially generated by Claude
pub mod gemmma4 {
    use serde::Serialize;
    use serde_json::{Map, Value};
    use thiserror::Error;
    use tracing::{Level, event};

    use crate::llm::dialog::{self, gemma4::{AssistantResponse, ToolCall}};

    pub fn assistant_response(res: impl AsRef<str>) -> AssistantResponse {
        let (mut rest, reasoning) =
            dialog::parse::tag(res.as_ref(), "<|channel>thought", "<channel|>")
                .map(|(rest, rea)| (rest, Some(rea.to_string())))
                .unwrap_or((res.as_ref().to_string(), None));
        let mut tool_calls = Vec::new();
        while let Some((rest_, tool_call)) =
            dialog::parse::tag(&rest, "<|tool_call>call:", "<tool_call|>")
        {
            tool_calls.push(parse_function_call(tool_call));
            if tool_calls.last().unwrap().is_err() {
                event!(
                    Level::WARN,
                    "unable to parse model tool call: {:?}",
                    tool_call
                );
            }
            rest = rest_;
        }
        AssistantResponse {
            reasoning,
            content: rest,
            tool_calls,
        }
    }

    fn parse_function_call(res: impl AsRef<str>) -> Result<ToolCall> {
        let res = res.as_ref();
        let name_arg_rep = regex::Regex::new(r#"([^{]*)\{([^}]*)\}"#).unwrap();
        let name_arg_groups = name_arg_rep
            .captures(res)
            .ok_or(ParseError::MalformedFunctionCall(res.to_string()))?;
        let (name, args) = (&name_arg_groups[1], &name_arg_groups[2]);
        Ok(ToolCall {
            name: name.to_string(),
            arguments: parse_argument(format!("{{{args}}}"))?,
        })
    }

    // ─── Error type ──────────────────────────────────────────────────────────────

    #[derive(Clone, Debug, Error, Serialize)]
    pub enum ParseError {
        #[error("malformed function call: {0:?}")]
        MalformedFunctionCall(String),

        #[error("unexpected end of input")]
        UnexpectedEof,

        #[error("unterminated string delimiter starting at {0:?}")]
        UnterminatedString(String),

        #[error("unterminated object key delimiter starting at {0:?}")]
        UnterminatedKey(String),

        #[error("expected ':' after object key but got {0:?}")]
        ExpectedColon(String),

        #[error("expected '}}' to close object but got {0:?}")]
        UnclosedObject(String),

        #[error("expected ']' to close array but got {0:?}")]
        UnclosedArray(String),

        #[error("invalid numeric literal {0:?}")]
        InvalidNumber(String),

        #[error("non-finite float value {0}")]
        NonFiniteFloat(f64),

        #[error("top-level value must be an object, got a non-object value")]
        NotAnObject,

        #[error("invalid or empty key at {0:?}")]
        InvalidKey(String),
    }

    pub type Result<T> = std::result::Result<T, ParseError>;

    // ─── Constants ───────────────────────────────────────────────────────────────

    const DELIM: &str = "<|\"|>";
    const DELIM_LEN: usize = DELIM.len();

    /// Parses a string encoded by the Jinja `format_argument` macro into a JSON
    /// object map.  Returns [`ParseError`] on malformed input instead of panicking.
    pub fn parse_argument(res: impl AsRef<str>) -> Result<Map<String, Value>> {
        let input = res.as_ref().trim();
        let (value, _) = parse_value(input)?;
        match value {
            Value::Object(map) => Ok(map),
            _ => Err(ParseError::NotAnObject),
        }
    }

    // ─── Internal helpers ────────────────────────────────────────────────────────

    /// Recursively parse a single value from the front of `s`.
    /// Returns `(parsed_value, remaining_input)`.
    fn parse_value(s: &str) -> Result<(Value, &str)> {
        let s = s.trim_start();

        if s.is_empty() {
            return Err(ParseError::UnexpectedEof);
        }

        if s.starts_with(DELIM) {
            // ── String ──────────────────────────────────────────────────────────
            let rest = &s[DELIM_LEN..];
            let end = rest
                .find(DELIM)
                .ok_or_else(|| ParseError::UnterminatedString(preview(s)))?;
            let string_val = &rest[..end];
            let remaining = &rest[end + DELIM_LEN..];
            Ok((Value::String(string_val.to_string()), remaining))
        } else if s.starts_with('{') {
            // ── Object ──────────────────────────────────────────────────────────
            parse_object(&s[1..])
        } else if s.starts_with('[') {
            // ── Array ───────────────────────────────────────────────────────────
            parse_array(&s[1..])
        } else if s.starts_with("true") {
            Ok((Value::Bool(true), &s["true".len()..]))
        } else if s.starts_with("false") {
            Ok((Value::Bool(false), &s["false".len()..]))
        } else if s.starts_with("null") {
            Ok((Value::Null, &s["null".len()..]))
        } else {
            // ── Number ──────────────────────────────────────────────────────────
            let end = s
                .find(|c: char| matches!(c, ',' | '}' | ']'))
                .unwrap_or(s.len());
            let token = s[..end].trim();
            let remaining = &s[end..];

            if let Ok(n) = token.parse::<i64>() {
                Ok((Value::Number(n.into()), remaining))
            } else if let Ok(f) = token.parse::<f64>() {
                let number =
                    serde_json::Number::from_f64(f).ok_or(ParseError::NonFiniteFloat(f))?;
                Ok((Value::Number(number), remaining))
            } else {
                Err(ParseError::InvalidNumber(token.to_string()))
            }
        }
    }

    /// Parse the inside of an object after the opening `{`.
    /// Returns `(Value::Object(...), remaining_after_closing_brace)`.
    fn parse_object(mut s: &str) -> Result<(Value, &str)> {
        let mut map = Map::new();

        loop {
            s = s.trim_start();

            if s.is_empty() {
                return Err(ParseError::UnclosedObject(preview(s)));
            }

            if s.starts_with('}') {
                return Ok((Value::Object(map), &s[1..]));
            }

            // Keys are either escaped (`<|"|>name<|"|>`) or bare (`name`).
            let key;
            if s.starts_with(DELIM) {
                // Escaped key
                let rest = &s[DELIM_LEN..];
                let key_end = rest
                    .find(DELIM)
                    .ok_or_else(|| ParseError::UnterminatedKey(preview(s)))?;
                key = rest[..key_end].to_string();
                s = &rest[key_end + DELIM_LEN..];
            } else {
                // Bare key: read everything up to the first ':'
                let key_end = s
                    .find(':')
                    .ok_or_else(|| ParseError::ExpectedColon(preview(s)))?;
                let raw = s[..key_end].trim();
                if raw.is_empty() {
                    return Err(ParseError::InvalidKey(preview(s)));
                }
                key = raw.to_string();
                // Leave s pointing at ':'; the block below will consume it.
                s = &s[key_end..];
            }

            // Consume the `:` separator
            s = s.trim_start();
            if !s.starts_with(':') {
                return Err(ParseError::ExpectedColon(preview(s)));
            }
            s = &s[1..];

            // Parse the value
            let (value, rest) = parse_value(s)?;
            map.insert(key, value);
            s = rest.trim_start();

            // Optional comma between entries
            if s.starts_with(',') {
                s = &s[1..];
            }
        }
    }

    /// Parse the inside of an array after the opening `[`.
    /// Returns `(Value::Array(...), remaining_after_closing_bracket)`.
    fn parse_array(mut s: &str) -> Result<(Value, &str)> {
        let mut items = Vec::new();

        loop {
            s = s.trim_start();

            if s.is_empty() {
                return Err(ParseError::UnclosedArray(preview(s)));
            }

            if s.starts_with(']') {
                return Ok((Value::Array(items), &s[1..]));
            }

            let (item, rest) = parse_value(s)?;
            items.push(item);
            s = rest.trim_start();

            // Optional comma between items
            if s.starts_with(',') {
                s = &s[1..];
            }
        }
    }

    /// Return a short preview of a string slice for use in error messages.
    fn preview(s: &str) -> String {
        const MAX: usize = 32;
        if s.len() <= MAX {
            s.to_string()
        } else {
            format!("{}…", &s[..MAX])
        }
    }

    // ─── Tests ───────────────────────────────────────────────────────────────────

    #[cfg(test)]
    mod tests {
        use super::*;
        use serde_json::json;

        // ── Happy-path tests ─────────────────────────────────────────────────────

        #[test]
        fn simple_string_value() {
            let input = r#"{<|"|>key<|"|>:<|"|>hello<|"|>}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["key"], json!("hello"));
        }

        #[test]
        fn boolean_values() {
            let input = r#"{<|"|>a<|"|>:true,<|"|>b<|"|>:false}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["a"], json!(true));
            assert_eq!(result["b"], json!(false));
        }

        #[test]
        fn numeric_value() {
            let input = r#"{<|"|>count<|"|>:42}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["count"], json!(42));
        }

        #[test]
        fn null_value() {
            let input = r#"{<|"|>x<|"|>:null}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["x"], json!(null));
        }

        #[test]
        fn nested_object() {
            let input = r#"{<|"|>outer<|"|>:{<|"|>inner<|"|>:<|"|>val<|"|>}}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["outer"], json!({"inner": "val"}));
        }

        #[test]
        fn array_of_strings() {
            let input = r#"{<|"|>items<|"|>:[<|"|>x<|"|>,<|"|>y<|"|>,<|"|>z<|"|>]}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["items"], json!(["x", "y", "z"]));
        }

        #[test]
        fn complex_nested() {
            let input = r#"{<|"|>args<|"|>:{<|"|>flag<|"|>:true,<|"|>values<|"|>:[1,2]},<|"|>name<|"|>:<|"|>tool<|"|>}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["name"], json!("tool"));
            assert_eq!(result["args"], json!({"flag": true, "values": [1, 2]}));
        }

        // ── Error-path tests ─────────────────────────────────────────────────────

        #[test]
        fn err_not_an_object() {
            let err = parse_argument(r#"[<|"|>a<|"|>]"#).unwrap_err();
            assert!(matches!(err, ParseError::NotAnObject));
        }

        #[test]
        fn err_unterminated_string() {
            let err = parse_argument(r#"{<|"|>key<|"|>:<|"|>oops}"#).unwrap_err();
            assert!(matches!(err, ParseError::UnterminatedString(_)));
        }

        #[test]
        fn err_unterminated_key() {
            let err = parse_argument(r#"{<|"|>oops}"#).unwrap_err();
            assert!(matches!(err, ParseError::UnterminatedKey(_)));
        }

        #[test]
        fn err_expected_colon() {
            let err = parse_argument(r#"{<|"|>key<|"|> <|"|>val<|"|>}"#).unwrap_err();
            assert!(matches!(err, ParseError::ExpectedColon(_)));
        }

        #[test]
        fn err_unexpected_eof() {
            let err = parse_argument("").unwrap_err();
            assert!(matches!(err, ParseError::UnexpectedEof));
        }

        #[test]
        fn err_invalid_number() {
            let err = parse_argument(r#"{<|"|>n<|"|>:notanumber}"#).unwrap_err();
            assert!(matches!(err, ParseError::InvalidNumber(_)));
        }

        // ── Bare-key (escape_keys=False) tests ──────────────────────────────────

        #[test]
        fn bare_key_number() {
            let result = parse_argument("{favorite_number:42}").unwrap();
            assert_eq!(result["favorite_number"], json!(42));
        }

        #[test]
        fn bare_key_string_value() {
            let input = r#"{name:<|"|>Alice<|"|>}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["name"], json!("Alice"));
        }

        #[test]
        fn bare_key_bool() {
            let result = parse_argument("{active:true}").unwrap();
            assert_eq!(result["active"], json!(true));
        }

        #[test]
        fn bare_key_mixed_with_escaped() {
            let input = r#"{count:3,<|"|>label<|"|>:<|"|>hi<|"|>}"#;
            let result = parse_argument(input).unwrap();
            assert_eq!(result["count"], json!(3));
            assert_eq!(result["label"], json!("hi"));
        }

        #[test]
        fn err_empty_bare_key() {
            let err = parse_argument("{:42}").unwrap_err();
            assert!(matches!(err, ParseError::InvalidKey(_)));
        }
    }
}
