// This test suite is generated by Claude at Mon May 4 14:21:26 UTC 2026

use std::time::Duration;

use futures::StreamExt;
use serde::{Deserialize, Serialize};
use tokio::time::timeout;
use tracing_test::traced_test;

use crate::polling::{
    Scheduler, error::TaskCancellationError, schedule::QueueType, task::TaskState,
    trigger::ScheduleTrigger,
};

// ---------------------------------------------------------------------------
// Test key type
// ---------------------------------------------------------------------------

/// A minimal key type that satisfies KeyContract.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
struct TestKey(u32);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// A cron expression that fires once per second – useful for "very soon"
/// tests.  Adjust if your minimum resolution differs.
fn every_second() -> ScheduleTrigger {
    ScheduleTrigger::Cron("* * * * * * *".to_string())
}

/// A cron expression that fires once per minute – useful for "far future"
/// tests so the sleep never actually elapses.
fn every_minute() -> ScheduleTrigger {
    ScheduleTrigger::Cron("0 * * * * * *".to_string())
}

fn scheduler() -> Scheduler<TestKey> {
    Scheduler::new()
}

// ---------------------------------------------------------------------------
// Construction
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn new_scheduler_has_no_schedules() {
    let s = scheduler();
    assert!(s.schedules().await.is_empty());
}

// ---------------------------------------------------------------------------
// add_schedule – IDs and persistence
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn add_schedule_returns_schedule_with_id_1_when_empty() {
    let s = scheduler();
    let schedule = s
        .add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");
    assert_eq!(schedule.id(), 1);
}

#[tokio::test]
#[traced_test]
async fn add_schedule_increments_id_for_each_new_schedule() {
    let s = scheduler();
    let a = s
        .add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");
    let b = s
        .add_schedule(every_second(), TestKey(2))
        .await
        .expect("valid cron");
    let c = s
        .add_schedule(every_minute(), TestKey(3))
        .await
        .expect("valid cron");

    assert_eq!(a.id(), 1);
    assert_eq!(b.id(), 2);
    assert_eq!(c.id(), 3);
}

#[tokio::test]
#[traced_test]
async fn add_schedule_persists_in_schedules_list() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(42))
        .await
        .expect("valid cron");
    s.add_schedule(every_minute(), TestKey(99))
        .await
        .expect("valid cron");

    let list = s.schedules().await;
    assert_eq!(list.len(), 2);

    let keys: Vec<_> = list.iter().map(|s| s.key().clone()).collect();
    assert!(keys.contains(&TestKey(42)));
    assert!(keys.contains(&TestKey(99)));
}

#[tokio::test]
#[traced_test]
async fn add_schedule_with_invalid_cron_returns_error() {
    let s = scheduler();
    let result = s
        .add_schedule(
            ScheduleTrigger::Cron("not a cron expression".to_string()),
            TestKey(1),
        )
        .await;
    assert!(result.is_err());
}

#[tokio::test]
#[traced_test]
async fn add_schedule_stores_provided_key() {
    let s = scheduler();
    let schedule = s
        .add_schedule(every_second(), TestKey(7))
        .await
        .expect("valid cron");
    assert_eq!(schedule.key(), &TestKey(7));
}

// ---------------------------------------------------------------------------
// schedules() accessor
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn schedules_returns_all_added_schedules() {
    let s = scheduler();
    for i in 0..5u32 {
        s.add_schedule(every_second(), TestKey(i))
            .await
            .expect("valid cron");
    }
    assert_eq!(s.schedules().await.len(), 5);
}

// ---------------------------------------------------------------------------
// until_next_reschedule
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn until_next_reschedule_resolves_after_add_schedule() {
    let s = scheduler();

    let notify_fut = s.until_next_reschedule();
    tokio::pin!(notify_fut);

    // Adding a schedule should send a notification.
    let (queue_type_result, _) =
        tokio::join!(notify_fut, s.add_schedule(every_second(), TestKey(1)));

    // First insertion creates a new queue.
    assert!(matches!(queue_type_result, Ok(QueueType::New)));
}

#[tokio::test]
#[traced_test]
async fn until_next_reschedule_second_insertion_reports_existing_queue() {
    let s = scheduler();

    // Insert once so a queue exists.
    s.add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");

    let notify_fut = s.until_next_reschedule();
    tokio::pin!(notify_fut);

    // Second insertion for the same key → Existing queue.
    let (queue_type_result, _) =
        tokio::join!(notify_fut, s.add_schedule(every_second(), TestKey(1)));

    assert!(matches!(queue_type_result, Ok(QueueType::Exising)));
}

// ---------------------------------------------------------------------------
// start_polling – global (key = None)
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn start_polling_yields_task_for_every_second_schedule() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");

    let mut stream = Box::pin(s.start_polling(None));

    // We expect a successful task to arrive within two seconds.
    let result = timeout(Duration::from_secs(2), stream.next())
        .await
        .expect("timed out waiting for task")
        .expect("stream ended unexpectedly");

    assert!(result.is_ok(), "expected Ok(Task), got: {:?}", result);
}

#[tokio::test]
#[traced_test]
async fn start_polling_task_key_matches_schedule_key() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(55))
        .await
        .expect("valid cron");

    let mut stream = Box::pin(s.start_polling(None));
    let task = timeout(Duration::from_secs(2), stream.next())
        .await
        .expect("timed out")
        .expect("stream ended")
        .expect("task error");

    assert_eq!(task.schedule().key(), &TestKey(55));
}

#[tokio::test]
#[traced_test]
async fn start_polling_yields_multiple_tasks_in_sequence() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");

    let stream = Box::pin(s.start_polling(None));

    // Collect the first three successful results, skipping cancellations.
    let results: Vec<_> = timeout(
        Duration::from_secs(5),
        stream
            .filter_map(|r| async move { r.ok() })
            .take(3)
            .collect(),
    )
    .await
    .expect("timed out collecting tasks");

    assert_eq!(results.len(), 3);
}

// ---------------------------------------------------------------------------
// start_polling – key-filtered
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn start_polling_with_key_only_yields_matching_key() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");
    s.add_schedule(every_second(), TestKey(2))
        .await
        .expect("valid cron");

    let key = TestKey(1);
    let mut stream = Box::pin(s.start_polling(Some(&key)));

    let task = timeout(Duration::from_secs(2), stream.next())
        .await
        .expect("timed out")
        .expect("stream ended")
        .expect("task error");

    assert_eq!(task.schedule().key(), &TestKey(1));
}

// ---------------------------------------------------------------------------
// start_polling – task state transitions
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn polled_task_is_in_running_state_when_yielded() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");

    let mut stream = Box::pin(s.start_polling(None));
    let task = timeout(Duration::from_secs(2), stream.next())
        .await
        .expect("timed out")
        .expect("stream ended")
        .expect("task error");

    // The scheduler sets state → Running before yielding the task.
    let state = task.state.read().await.clone();
    assert_eq!(state, TaskState::Running);
}

#[tokio::test]
#[traced_test]
async fn polled_task_transitions_to_finished_after_next_poll() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");

    let mut stream = Box::pin(s.start_polling(None));

    let task = timeout(Duration::from_secs(2), stream.next())
        .await
        .expect("timed out")
        .expect("stream ended")
        .expect("task error");

    let state_handle = task.state.clone();

    // Advance the stream so the scheduler can write TaskState::Finished.
    let _ = timeout(Duration::from_secs(2), stream.next()).await;

    let state = state_handle.read().await.clone();
    assert_eq!(state, TaskState::Finished);
}

// ---------------------------------------------------------------------------
// start_polling – cancellation
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn start_polling_emits_cancellation_when_earlier_schedule_inserted() {
    let s = scheduler();

    // Insert a far-future schedule so the poller will be sleeping.
    s.add_schedule(every_minute(), TestKey(1))
        .await
        .expect("valid cron");

    let mut stream = Box::pin(s.start_polling(None));

    // Spawn a task that inserts an earlier schedule shortly after polling
    // starts.  We use every_second() which fires sooner than every_minute().
    tokio::spawn({
        // We need an owned handle; clone the scheduler or use Arc.
        // Adjust if Scheduler is wrapped in Arc in your real code.
        async move {
            tokio::time::sleep(Duration::from_millis(100)).await;
            // (This requires Scheduler to be Clone or Arc-wrapped in real use;
            //  adapt accordingly.)
        }
    });

    // The first item yielded should be a cancellation error because a
    // new, earlier schedule was inserted while we were waiting.
    // NOTE: this test assumes the scheduler detects the earlier trigger and
    // cancels.  The exact timing may require adjusting the sleep above.
    let first = timeout(Duration::from_secs(2), stream.next())
        .await
        .expect("timed out waiting for cancellation")
        .expect("stream ended");

    assert!(
        matches!(first, Err(TaskCancellationError)),
        "expected TaskCancellationError, got Ok(_)"
    );
}

// ---------------------------------------------------------------------------
// start_polling – empty queue
// ---------------------------------------------------------------------------

#[tokio::test]
#[traced_test]
async fn start_polling_on_empty_scheduler_returns_immediately() {
    let s = scheduler();
    let mut stream = Box::pin(s.start_polling(None));

    // With no schedules the stream should end without blocking.
    let result = timeout(Duration::from_millis(100), stream.next()).await;
    assert!(
        matches!(result, Ok(None)),
        "expected stream to end immediately, got {:?}",
        result
    );
}

#[tokio::test]
#[traced_test]
async fn start_polling_with_unknown_key_returns_immediately() {
    let s = scheduler();
    s.add_schedule(every_second(), TestKey(1))
        .await
        .expect("valid cron");

    let unknown = TestKey(999);
    let mut stream = Box::pin(s.start_polling(Some(&unknown)));

    let result = timeout(Duration::from_millis(100), stream.next()).await;
    assert!(
        matches!(result, Ok(None)),
        "expected stream to end immediately for unknown key, got {:?}",
        result
    );
}
